2019-08-09 21:30:21 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [INFO]: test 
2019-08-09 21:30:21 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [ERROR]: test2 
2019-08-09 21:31:04 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [INFO]: test 
2019-08-09 21:31:04 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [ERROR]: test2 
2019-08-09 21:31:38 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [INFO]: test 
2019-08-09 21:31:38 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [ERROR]: test2 
2019-08-09 21:33:24 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [INFO]: test 
2019-08-09 21:33:24 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [ERROR]: test2 
2019-08-09 21:33:38 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [INFO]: test 
2019-08-09 21:33:38 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [ERROR]: test2 
2019-08-09 21:33:40 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [INFO]: test 
2019-08-09 21:33:40 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [ERROR]: test2 
2019-08-09 21:33:55 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [INFO]: test 
2019-08-09 21:33:55 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [ERROR]: test2 
2019-08-09 21:34:10 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [INFO]: test 
2019-08-09 21:34:10 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [ERROR]: test2 
2019-08-09 21:34:33 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [INFO]: test 
2019-08-09 21:34:33 /Users/netease/Documents/git/git-201808-newbie-xianwei01/python/myPyTest/111.py [ERROR]: test2 
